package administraciondeempleados.view;

import administraciondeempleados.Horario;
import administraciondeempleados.Gerente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import prueb.DBConnect;

/**
 *
 * @author SONY VAIO
 */
public class DiaHorarios extends javax.swing.JDialog {

    int xPos, yPos;
    private DiaHorario diaHorario;
    private Horario horario;
    private Gerente gerente;
    private DBConnect dbConnect;
    private Connection connection;
    private String sql;
    private PreparedStatement ps;
    private ResultSet result;

    /**
     * Creates new form DiaHorarios
     */
    public DiaHorarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DiaHorarios(java.awt.Frame parent, boolean modal, Gerente gerente) {
        this(parent, modal);
        this.gerente = gerente;
        this.horario = new Horario();
        modelTableHorarios.cargarModelo(gerente.getEmpresa());
        dbConnect = new DBConnect();
    }

    public DiaHorarios(java.awt.Frame parent, boolean modal, List<Horario> horarioList, Gerente gerente) {
        this(parent, modal);        
        this.gerente = gerente;
        this.horario = new Horario();
        modelTableHorarios.cargarModeloEmpleado(horarioList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelTableHorarios = new administraciondeempleados.view.ModelTableHorarios();
        lblHorarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorarios = new javax.swing.JTable();
        btnAgregarHorario = new javax.swing.JButton();
        btnEliminarHorario = new javax.swing.JButton();
        btnEditarHorario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHorarios.setBackground(new java.awt.Color(255, 255, 255));
        lblHorarios.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblHorarios.setForeground(new java.awt.Color(51, 51, 51));
        lblHorarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHorarios.setText("HORARIOS");

        tblHorarios.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        tblHorarios.setModel(modelTableHorarios);
        jScrollPane1.setViewportView(tblHorarios);

        btnAgregarHorario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        btnAgregarHorario.setText("Agregar Horario");
        btnAgregarHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarHorarioMouseClicked(evt);
            }
        });
        btnAgregarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHorarioActionPerformed(evt);
            }
        });

        btnEliminarHorario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        btnEliminarHorario.setText("Eliminar Horario");
        btnEliminarHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarHorarioMouseClicked(evt);
            }
        });
        btnEliminarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHorarioActionPerformed(evt);
            }
        });

        btnEditarHorario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        btnEditarHorario.setText("Editar Horario");
        btnEditarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 921, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(370, 370, 370)
                            .addComponent(lblHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(520, 520, 520)
                            .addComponent(btnAgregarHorario)
                            .addGap(8, 8, 8)
                            .addComponent(btnEditarHorario)
                            .addGap(12, 12, 12)
                            .addComponent(btnEliminarHorario)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAgregarHorario)
                        .addComponent(btnEditarHorario)
                        .addComponent(btnEliminarHorario))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarHorarioMouseClicked
        diaHorario = new DiaHorario(null, true, gerente);
        //diaHorario.setGerente(gerente);
        diaHorario.setVisible(true);
        modelTableHorarios.cargarModelo(gerente.getEmpresa());
    }//GEN-LAST:event_btnAgregarHorarioMouseClicked

    private void btnAgregarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarHorarioActionPerformed

    private void btnEliminarHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarHorarioMouseClicked
        //modelTableHorarios.getSelectedValue();
    }//GEN-LAST:event_btnEliminarHorarioMouseClicked


    private void btnEliminarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHorarioActionPerformed
        Horario horario = gerente.getEmpresa().getHorarioList().get(tblHorarios.getSelectedRow());
        eliminarHorarioDB(horario);
        gerente.getEmpresa().getHorarioList().remove(horario);
        modelTableHorarios.cargarModelo(gerente.getEmpresa());
    }//GEN-LAST:event_btnEliminarHorarioActionPerformed

    private void eliminarHorarioDB(Horario horario) {
        try {
            connection = dbConnect.conectar();
            long id = retornarID(horario.getTipo());
            eliminarIdHorario_Dias_Laborables(id);
            sql = "DELETE FROM \"horarios\" WHERE id= " + id;
            ps = connection.prepareStatement(sql);
            ps.execute();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se puede eliminar el horario");
            System.out.println("error al eliminar horario " + e.getMessage());
        } finally {
            dbConnect.desconectar();
        }
    }

    private long retornarID(String tipo) {
        long id = 0;
        try {
            String query = "SELECT id FROM \"horarios\" WHERE tipo='" + tipo + "' GROUP BY id";
            ps = connection.prepareStatement(query);
            result = ps.executeQuery();
            while (result.next()) {
                id = result.getLong("id");
            }
            System.out.println(id);
            return id;
        } catch (Exception e) {
            System.out.println("no se puedo retornar el id" + e.getMessage());
        }
        return 0;
    }

    private void eliminarIdHorario_Dias_Laborables(long id) {
        try {
            sql = "DELETE FROM \"horarios_dias_laborables\" WHERE id_horarios= " + id + ';';
            ps = connection.prepareStatement(sql);
            ps.execute();
        } catch (Exception e) {
            System.out.println("error al eliminar el id de horario en dias laborables xd " + e.getMessage());
        }
    }

    public Horario obtenerHorario() {
        if (tblHorarios.getSelectedRow() >= 0) {
            horario = gerente.getEmpresa().getHorarioList().get(tblHorarios.getSelectedRow());
        }
        return horario;
    }
    private void btnEditarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarHorarioActionPerformed
        diaHorario = new DiaHorario(null, true, gerente);
        diaHorario.setIndice(tblHorarios.getSelectedRow());
        diaHorario.completarCampos();
        diaHorario.setVisible(true);
        modelTableHorarios.cargarModelo(gerente.getEmpresa());
    }//GEN-LAST:event_btnEditarHorarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiaHorarios dialog = new DiaHorarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JLabel getLblHorarios() {
        return lblHorarios;
    }

    public void setLblHorarios(JLabel lblHorarios) {
        this.lblHorarios = lblHorarios;
    }

    public JTable getTblHorarios() {
        return tblHorarios;
    }

    public void setTblHorarios(JTable tblHorarios) {
        this.tblHorarios = tblHorarios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarHorario;
    private javax.swing.JButton btnEditarHorario;
    private javax.swing.JButton btnEliminarHorario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHorarios;
    private administraciondeempleados.view.ModelTableHorarios modelTableHorarios;
    private javax.swing.JTable tblHorarios;
    // End of variables declaration//GEN-END:variables
}
