package administraciondeempleados.gui;

import administraciondeempleados.Contrato;
import administraciondeempleados.Empleado;
import administraciondeempleados.Puesto;
import administraciondeempleados.Rol;
import administraciondeempleados.Departamento;
import administraciondeempleados.Empresa;
import administraciondeempleados.Horario;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario iTC
 */
public class NewJFrame extends javax.swing.JFrame {

    Empresa empresa;
    Empleado empleado;
    Departamento departamento;
    Calendar horaActual;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        empresa = new Empresa("Tienda", 1990, "Manufactura");
        empleado = new Empleado();
        departamento = new Departamento("Finanzas", 1, 40);
        empresa.getDepartamentoList().add(departamento);
        empresa.getRolList().add(new Rol("Contable"));
        empresa.getRolList().add(new Rol("Administrador"));
        empresa.getHorarioList().add(new Horario("Matutino"));
        empresa.getHorarioList().add(new Horario("Vespertino"));
        empresa.setHoraEntrada(7, 30);
        crearEmpleados();
        this.horaActual = Calendar.getInstance();
    }

    private void crearEmpleados() {
        Empleado e1 = new Empleado();
        Empleado e2 = new Empleado();
        Empleado e3 = new Empleado();
        empleado.setHorario(new Horario("Matutino"));
        e1.setId("2");
        e1.setNombre("Javier Eduardo");
        e1.setApellido("Gonzalez Campos");
        e1.setDepartamento(departamento);
        e1.setPuesto(new Puesto("empleado"));
        e1.setRol(new Rol("Administrador", e1.getPuesto(), departamento));
        e1.setHorario(new Horario("Vespertino"));

        e2.setId("3");
        e2.setNombre("Lucia Fernanda");
        e2.setApellido("Romero Agila");
        e2.setDepartamento(departamento);
        e2.setPuesto(new Puesto("Supervisor"));
        e2.setRol(new Rol("Contable", e2.getPuesto(), departamento));
        e2.setHorario(new Horario("Matutino"));

        e3.setId("4");
        e3.setNombre("Lucas Geronimo");
        e3.setApellido("Hernandez Costa");
        e3.setDepartamento(departamento);
        e3.setPuesto(new Puesto("Jefe"));
        e3.setRol(new Rol("Contable", e2.getPuesto(), departamento));
        e3.setHorario(new Horario("Vespertino"));

        departamento.getTrabajadorList().add(e1);
        departamento.getTrabajadorList().add(e2);
        departamento.getTrabajadorList().add(e3);
        departamento.getTrabajadorList().add(empleado); // primero ejecutar el del perfil, para que se cree el empleado

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_departamento = new javax.swing.JButton();
        btn_busqueda = new javax.swing.JButton();
        btn_asistencia = new javax.swing.JButton();
        btn_verAsistencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Perfil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 676));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_departamento.setText("Departamento");
        btn_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_departamentoActionPerformed(evt);
            }
        });

        btn_busqueda.setText("busqueda");
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });

        btn_asistencia.setText("Asistencia");
        btn_asistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asistenciaActionPerformed(evt);
            }
        });

        btn_verAsistencia.setText("Ver asistencia");
        btn_verAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_departamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_busqueda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btn_verAsistencia))
                        .addComponent(btn_asistencia)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_departamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_busqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_asistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_verAsistencia)
                        .addGap(0, 540, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        empleado.setId("1");
        empleado.setApellido("Ortega");
        empleado.setCedula("3050093776");
        empleado.setCiudad("Loja");
        empleado.setDireccion("Av Eugenio Espejo");
        empleado.setNombre("Jorge");
        empleado.setSexo('m');
        empleado.setTelefono("0994956460");
        empleado.setContrato(new Contrato(true));
        empleado.setCorreoEmpresarial("correoEmpresarial@empresa.gob");
        empleado.setCorreoPersonal("jorde.d.ortega@unl.edu.ec");
        empleado.setDepartamento(departamento);
        empleado.setPuesto(new Puesto("empleado"));
        empleado.setRol(new Rol("Contable", empleado.getPuesto(), empleado.getDepartamento()));
        empleado.setUsuario("Daniel21");
        empleado.setHorario(new Horario("Matutino"));

        Perfil p = new Perfil(empleado);
        p.setSize(696, 656);
        p.setLocation(0, 0);
        jPanel1.removeAll();
        jPanel1.add(p);
        jPanel1.revalidate();
        jPanel1.repaint();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_departamentoActionPerformed
        DepartamentoGUi d = new DepartamentoGUi(empleado.getDepartamento());
        d.setSize(1011, 476);
        d.setLocation(0, 0);
        jPanel1.removeAll();
        jPanel1.add(d);
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_btn_departamentoActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed
        Busqueda b = new Busqueda(empresa);
        b.setSize(1035, 460);
        b.setLocation(0, 0);
        jPanel1.removeAll();
        jPanel1.add(b);
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void btn_asistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asistenciaActionPerformed
        Calendar horaEntrada = empresa.getHoraEntrada();
        //comprobar si ya marco asistencia para que se desactive(confiemos en que todo ira bien)
        //si hay tiempo ponerle un metodo para que compruebe pasado una hora (8 si ha marcado asistencia o no, si no hay nada guardado en su asistenciaList, asignarFaltaIjustificada automaticamente
        if (horaActual.get(Calendar.HOUR_OF_DAY) == horaActual.get(Calendar.HOUR_OF_DAY)) {
            AsignacionAsistencia asignacionAsistencia
                    = new AsignacionAsistencia(this, true, empleado.getAsistenciaList(), empresa.getHoraEntrada());
            asignacionAsistencia.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "no se puede marcar asistencia todavia"); //mas tarde cambiar el mensaje
        }
    }//GEN-LAST:event_btn_asistenciaActionPerformed

    private void btn_verAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verAsistenciaActionPerformed
        AsistenciaGUI asistenciaGUI = new AsistenciaGUI(this, true, empleado);
        asistenciaGUI.setVisible(true);
    }//GEN-LAST:event_btn_verAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_asistencia;
    private javax.swing.JButton btn_busqueda;
    private javax.swing.JButton btn_departamento;
    private javax.swing.JButton btn_verAsistencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
